language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get -y install libblas3 liblapack3 python-setuptools
install:
  - pip install --upgrade pip
  - pip install pytest --upgrade
  - pip install -r requirements.txt
# command to run tests
cache: pip
script:
  - pip install -e .
  - python -m  pytest tests/
   # or py.test for Python versions 3.5 and below
